export const employeeStep1Data = [
  {
    full_name: "Aarav Sharma",
    profile_photo: "https://randomuser.me/api/portraits/men/1.jpg",
    short_bio: "Curious developer exploring emerging technologies.",
    current_position: "Frontend Developer",
    career_goal: "Become a Lead UI Engineer.",
    linkedin_url: "https://linkedin.com/in/aaravsharma",
    github_url: "https://github.com/aaravsharma",
    portfolio_url: "https://aarav.dev",
    city: "Bangalore",
    country: "India",
  },
  {
    full_name: "Sophia Turner",
    profile_photo: "https://randomuser.me/api/portraits/women/2.jpg",
    short_bio: "Motivated digital strategist passionate about SaaS.",
    current_position: "Marketing Associate",
    career_goal: "CMO at a tech-first startup.",
    linkedin_url: "https://linkedin.com/in/sophiaturner",
    github_url: "https://github.com/sophiamarkets",
    portfolio_url: "https://sophiaturner.me",
    city: "San Francisco",
    country: "USA",
  },
  {
    full_name: "Kabir Menon",
    profile_photo: "https://randomuser.me/api/portraits/men/3.jpg",
    short_bio: "Full-stack tinkerer and robotics enthusiast.",
    current_position: "Software Engineer 1",
    career_goal: "CTO of a robotics company.",
    linkedin_url: "https://linkedin.com/in/kabirmenon",
    github_url: "https://github.com/kabirm",
    portfolio_url: "https://kabir.tech",
    city: "Delhi",
    country: "India",
  },
  {
    full_name: "Emily Carter",
    profile_photo: "https://randomuser.me/api/portraits/women/4.jpg",
    short_bio: "Building beautiful user experiences.",
    current_position: "Product Designer",
    career_goal: "Design lead in an early-stage unicorn.",
    linkedin_url: "https://linkedin.com/in/emilycarter",
    github_url: "https://github.com/emilydesigns",
    portfolio_url: "https://emilycarter.design",
    city: "Toronto",
    country: "Canada",
  },
  {
    full_name: "Lucas Meyer",
    profile_photo: "https://randomuser.me/api/portraits/men/5.jpg",
    short_bio: "Cloud enthusiast and platform engineer.",
    current_position: "DevOps Engineer",
    career_goal: "Senior Cloud Architect.",
    linkedin_url: "https://linkedin.com/in/lucasmeyer",
    github_url: "https://github.com/lmeyer",
    portfolio_url: "https://lucasmeyer.dev",
    city: "Berlin",
    country: "Germany",
  },

  //------------------ NEW 20 YOU REQUESTED ------------------//

  {
    full_name: "Maya Kapoor",
    profile_photo: "https://randomuser.me/api/portraits/women/15.jpg",
    short_bio: "Tech enthusiast deeply passionate about fintech.",
    current_position: "Data Analyst",
    career_goal: "Transition to Machine Learning Engineer.",
    linkedin_url: "https://linkedin.com/in/mayakapoor",
    github_url: "https://github.com/mayakp",
    portfolio_url: "https://maya.ai",
    city: "Mumbai",
    country: "India",
  },
  {
    full_name: "James Foster",
    profile_photo: "https://randomuser.me/api/portraits/men/16.jpg",
    short_bio: "Entrepreneur-turned-developer with a builder mindset.",
    current_position: "Full Stack Developer",
    career_goal: "Launch a SaaS automation platform.",
    linkedin_url: "https://linkedin.com/in/jamesfoster",
    github_url: "https://github.com/jfosterdev",
    portfolio_url: "https://jamesbuilds.dev",
    city: "Austin",
    country: "USA",
  },
  {
    full_name: "Olivia Martinez",
    profile_photo: "https://randomuser.me/api/portraits/women/17.jpg",
    short_bio: "Creative storyteller and brand strategist.",
    current_position: "Content Strategist",
    career_goal: "Creative Director at a global brand.",
    linkedin_url: "https://linkedin.com/in/omartinez",
    github_url: "https://github.com/oliviacreates",
    portfolio_url: "https://oliviam.art",
    city: "Barcelona",
    country: "Spain",
  },
  {
    full_name: "Rohit Singh",
    profile_photo: "https://randomuser.me/api/portraits/men/18.jpg",
    short_bio: "Writing scalable backend systems with microservices.",
    current_position: "Backend Engineer",
    career_goal: "Architect distributed systems.",
    linkedin_url: "https://linkedin.com/in/rohitsingh",
    github_url: "https://github.com/rohitdev",
    portfolio_url: "https://rohit.codes",
    city: "Hyderabad",
    country: "India",
  },
  {
    full_name: "Zara Ali",
    profile_photo: "https://randomuser.me/api/portraits/women/19.jpg",
    short_bio: "Focused on UI accessibility and inclusive design.",
    current_position: "UX Researcher",
    career_goal: "Lead design at a health-tech company.",
    linkedin_url: "https://linkedin.com/in/zaraali",
    github_url: "https://github.com/uxzara",
    portfolio_url: "https://zaraui.design",
    city: "Dubai",
    country: "UAE",
  },
  {
    full_name: "Daniel Green",
    profile_photo: "https://randomuser.me/api/portraits/men/20.jpg",
    short_bio: "Former finance analyst pivoting into tech.",
    current_position: "Junior Developer",
    career_goal: "Become a blockchain developer.",
    linkedin_url: "https://linkedin.com/in/danielgreen",
    github_url: "https://github.com/dgreenjunior",
    portfolio_url: "https://daniel.codes",
    city: "London",
    country: "UK",
  },
  {
    full_name: "Harini Prakash",
    profile_photo: "https://randomuser.me/api/portraits/women/21.jpg",
    short_bio: "Story-driven creative digital marketer.",
    current_position: "SEO Specialist",
    career_goal: "Build a content-led SaaS growth channel.",
    linkedin_url: "https://linkedin.com/in/harinip",
    github_url: "https://github.com/harinimarketer",
    portfolio_url: "https://harinidigital.com",
    city: "Chennai",
    country: "India",
  },
  {
    full_name: "Leo Moretti",
    profile_photo: "https://randomuser.me/api/portraits/men/22.jpg",
    short_bio: "Tackling interesting problems with elegant engineering.",
    current_position: "ML Engineer",
    career_goal: "Research GenAI agent systems.",
    linkedin_url: "https://linkedin.com/in/leomoretti",
    github_url: "https://github.com/leoml",
    portfolio_url: "https://leomoretti.ai",
    city: "Milan",
    country: "Italy",
  },
  {
    full_name: "Hiro Tanaka",
    profile_photo: "https://randomuser.me/api/portraits/men/23.jpg",
    short_bio: "Passionate about robotics and autonomous systems.",
    current_position: "Embedded Systems Engineer",
    career_goal: "Lead robotics innovation lab.",
    linkedin_url: "https://linkedin.com/in/hirotanaka",
    github_url: "https://github.com/hiroembedded",
    portfolio_url: "https://hirobotics.jp",
    city: "Tokyo",
    country: "Japan",
  },
  {
    full_name: "Amelia Brooks",
    profile_photo: "https://randomuser.me/api/portraits/women/24.jpg",
    short_bio: "Helping companies discover their brand voice.",
    current_position: "Brand Consultant",
    career_goal: "Start a digital brand studio.",
    linkedin_url: "https://linkedin.com/in/ameliabrooks",
    github_url: "https://github.com/ameliabrand",
    portfolio_url: "https://ameliabrooks.art",
    city: "Sydney",
    country: "Australia",
  },
  {
    full_name: "Noah Adams",
    profile_photo: "https://randomuser.me/api/portraits/men/25.jpg",
    short_bio: "Optimizing UI performance and developer experience.",
    current_position: "Frontend Engineer",
    career_goal: "Lead frontend for a SaaS scale-up.",
    linkedin_url: "https://linkedin.com/in/noahadams",
    github_url: "https://github.com/noahcodes",
    portfolio_url: "https://noah.codes",
    city: "Vancouver",
    country: "Canada",
  },
  {
    full_name: "Priya Desai",
    profile_photo: "https://randomuser.me/api/portraits/women/26.jpg",
    short_bio: "Turning messy data into clear strategy.",
    current_position: "Data Visualization Engineer",
    career_goal: "Head of Analytics at a global company.",
    linkedin_url: "https://linkedin.com/in/priyadesai",
    github_url: "https://github.com/priyadata",
    portfolio_url: "https://priya.io",
    city: "Pune",
    country: "India",
  },
  {
    full_name: "Ahmed Hassan",
    profile_photo: "https://randomuser.me/api/portraits/men/27.jpg",
    short_bio: "Curious engineer exploring ethical AI.",
    current_position: "Machine Learning Intern",
    career_goal: "PhD + AI Ethics startup.",
    linkedin_url: "https://linkedin.com/in/ahmedhassan",
    github_url: "https://github.com/ahmedai",
    portfolio_url: "https://ahmedresearch.ai",
    city: "Cairo",
    country: "Egypt",
  },
  {
    full_name: "Natalie Wong",
    profile_photo: "https://randomuser.me/api/portraits/women/28.jpg",
    short_bio: "Vision-driven product builder.",
    current_position: "Associate PM",
    career_goal: "Generalist CTO in a deep tech field.",
    linkedin_url: "https://linkedin.com/in/nataliewong",
    github_url: "https://github.com/nataliepm",
    portfolio_url: "https://productbynatalie.com",
    city: "Hong Kong",
    country: "China",
  },
  {
    full_name: "Benjamin Cruz",
    profile_photo: "https://randomuser.me/api/portraits/men/29.jpg",
    short_bio: "Capturing stories through interactive design.",
    current_position: "Creative Technologist",
    career_goal: "Design immersive AR/VR storytelling apps.",
    linkedin_url: "https://linkedin.com/in/bencruz",
    github_url: "https://github.com/cruzcreative",
    portfolio_url: "https://cruz.design",
    city: "Los Angeles",
    country: "USA",
  },
  {
    full_name: "Sara Johansson",
    profile_photo: "https://randomuser.me/api/portraits/women/30.jpg",
    short_bio: "Designing intuitive digital experiences.",
    current_position: "UX Consultant",
    career_goal: "Work with government digital services.",
    linkedin_url: "https://linkedin.com/in/sarajohansson",
    github_url: "https://github.com/sjdesign",
    portfolio_url: "https://sarajohansson.design",
    city: "Stockholm",
    country: "Sweden",
  },
  {
    full_name: "Mateo Rivera",
    profile_photo: "https://randomuser.me/api/portraits/men/31.jpg",
    short_bio: "Combining engineering with financial strategies.",
    current_position: "Quantitative Analyst",
    career_goal: "Start a crypto algo trading firm.",
    linkedin_url: "https://linkedin.com/in/mateorivera",
    github_url: "https://github.com/mateoquant",
    portfolio_url: "https://mateoalgo.com",
    city: "Mexico City",
    country: "Mexico",
  },
  {
    full_name: "Grace Park",
    profile_photo: "https://randomuser.me/api/portraits/women/32.jpg",
    short_bio: "Transforming ideas into lovable products.",
    current_position: "Junior Product Designer",
    career_goal: "Lead product design at a global startup.",
    linkedin_url: "https://linkedin.com/in/gracepark",
    github_url: "https://github.com/graceui",
    portfolio_url: "https://grace.design",
    city: "Seoul",
    country: "South Korea",
  },
  {
    full_name: "Ivan Petrov",
    profile_photo: "https://randomuser.me/api/portraits/men/33.jpg",
    short_bio: "Optimizing performance and resilience of distributed systems.",
    current_position: "Systems Engineer",
    career_goal: "Resilience architect for large-scale systems.",
    linkedin_url: "https://linkedin.com/in/ivanpetrov",
    github_url: "https://github.com/ivanengineer",
    portfolio_url: "https://ivan.dev",
    city: "Moscow",
    country: "Russia",
  },
];

export const employeeStep2Data = [
  {
    skill_tags: ["React", "Tailwind", "Javascript"],
    expertise_summary: "Frontend specialist focusing on pixel-perfect UI.",
    years_of_experience: "2",
    tech_stack: ["React", "TailwindCSS", "Next.js"],
    open_to_roles: ["Frontend Developer", "Junior UI Engineer"],
    availability: "Full-time",
  },
  {
    skill_tags: ["SEO", "Analytics", "HubSpot"],
    expertise_summary: "Marketing automation and paid ads optimization.",
    years_of_experience: "3",
    tech_stack: ["HubSpot", "SEMRush", "Webflow"],
    open_to_roles: ["Marketing Assistant", "Growth Analyst"],
    availability: "Remote",
  },
  {
    skill_tags: ["Python", "Flask", "MongoDB"],
    expertise_summary: "Full-stack developer strong in backend logic.",
    years_of_experience: "1",
    tech_stack: ["Node.js", "Flask", "Docker"],
    open_to_roles: ["Backend Developer", "Full-Stack Developer"],
    availability: "Full-time",
  },
  {
    skill_tags: ["UI/UX", "Wireframing", "Figma"],
    expertise_summary: "User-first designer with strong research approach.",
    years_of_experience: "4",
    tech_stack: ["Figma", "Adobe XD", "Miro"],
    open_to_roles: ["Product Designer", "UX Researcher"],
    availability: "Part-time",
  },
  {
    skill_tags: ["AWS", "Automation", "Linux", "Terraform"],
    expertise_summary: "Infrastructure automation and server operations.",
    years_of_experience: "5",
    tech_stack: ["AWS", "Docker", "Terraform", "Kubernetes"],
    open_to_roles: ["DevOps Engineer", "Cloud Engineer"],
    availability: "Full-time",
  },

  // -------------------- NEW 20 -------------------- //

  {
    skill_tags: ["SQL", "Tableau", "Python"],
    expertise_summary: "Extracts insights from business and product data.",
    years_of_experience: "3",
    tech_stack: ["Tableau", "Snowflake", "PowerBI"],
    open_to_roles: ["Data Analyst", "ML Trainee"],
    availability: "Hybrid",
  },
  {
    skill_tags: ["React", "Node.js", "TypeScript"],
    expertise_summary: "Full-stack dev with growing interest in Web3.",
    years_of_experience: "4",
    tech_stack: ["React", "Express", "PostgreSQL"],
    open_to_roles: ["Full-Stack Engineer", "Founding Engineer"],
    availability: "Full-time",
  },
  {
    skill_tags: ["Copywriting", "Brand Strategy", "Content Marketing"],
    expertise_summary: "Digital storyteller for fast-growing brands.",
    years_of_experience: "5",
    tech_stack: ["Notion", "Canva", "Meta Ads Manager"],
    open_to_roles: ["Brand Strategist", "Marketing Lead"],
    availability: "Remote",
  },
  {
    skill_tags: ["Node.js", "Microservices", "SQL"],
    expertise_summary: "Specialized in real-time backend systems.",
    years_of_experience: "4",
    tech_stack: ["Node.js", "Redis", "Docker", "RabbitMQ"],
    open_to_roles: ["Backend Engineer", "Systems Engineer"],
    availability: "Full-time",
  },
  {
    skill_tags: ["Figma", "Empathy Mapping", "Usability Engineering"],
    expertise_summary: "Human-centered design focused on accessibility.",
    years_of_experience: "3",
    tech_stack: ["Figma", "Maze", "Framer"],
    open_to_roles: ["UX Researcher", "Product Designer"],
    availability: "Part-time",
  },
  {
    skill_tags: ["Python", "Machine Learning", "TensorFlow"],
    expertise_summary: "Engineer applying ML models to real-world problems.",
    years_of_experience: "2",
    tech_stack: ["TensorFlow", "PyTorch", "Airflow"],
    open_to_roles: ["ML Engineer", "Research Assistant"],
    availability: "Full-time",
  },
  {
    skill_tags: ["React", "Next.js", "Web Performance"],
    expertise_summary: "Frontend optimization + design systems.",
    years_of_experience: "3",
    tech_stack: ["Next.js", "Tailwind", "Vercel"],
    open_to_roles: ["Frontend Developer", "UI Developer"],
    availability: "Full-time",
  },
  {
    skill_tags: ["D3.js", "Data Visualization", "Python"],
    expertise_summary: "Transforms raw numbers into meaningful visual stories.",
    years_of_experience: "4",
    tech_stack: ["D3.js", "Plotly", "Pandas"],
    open_to_roles: ["Data Viz Engineer", "BI Developer"],
    availability: "Remote",
  },
  {
    skill_tags: ["AI Ethics", "Python", "Research Writing"],
    expertise_summary: "Works at the intersection of technology and policy.",
    years_of_experience: "1",
    tech_stack: ["Python", "HuggingFace", "Colab"],
    open_to_roles: ["AI Research Analyst", "ML Assistant"],
    availability: "Remote",
  },
  {
    skill_tags: ["Product Thinking", "User Mapping", "Roadmapping"],
    expertise_summary: "Builds product strategy aligned with user needs.",
    years_of_experience: "2",
    tech_stack: ["Notion", "Figma", "Jira"],
    open_to_roles: ["Product Manager", "Associate PM"],
    availability: "Hybrid",
  },
  {
    skill_tags: ["Unity", "3D Design", "XR Development"],
    expertise_summary: "Creates immersive user experiences for AR/VR.",
    years_of_experience: "5",
    tech_stack: ["Unity", "Blender", "WebXR"],
    open_to_roles: ["XR Developer", "Creative Engineer"],
    availability: "Full-time",
  },
  {
    skill_tags: ["UI/UX", "Brand Identity", "Prototyping"],
    expertise_summary: "Designs intuitive flows that delight users.",
    years_of_experience: "4",
    tech_stack: ["Figma", "Sketch", "Framer"],
    open_to_roles: ["Product Designer", "UX Lead"],
    availability: "Part-time",
  },
  {
    skill_tags: ["Rust", "Linux", "Networking"],
    expertise_summary: "Systems engineer optimizing performance-heavy apps.",
    years_of_experience: "6",
    tech_stack: ["Rust", "C", "Docker"],
    open_to_roles: ["Systems Engineer", "Infra Engineer"],
    availability: "Full-time",
  },
  {
    skill_tags: ["Solidity", "Blockchain", "Smart Contracts"],
    expertise_summary: "Builds decentralized applications and automation.",
    years_of_experience: "3",
    tech_stack: ["Solidity", "Hardhat", "Polygon"],
    open_to_roles: ["Web3 Developer", "Blockchain Engineer"],
    availability: "Remote",
  },
  {
    skill_tags: ["Finance Modeling", "Python", "Data Mining"],
    expertise_summary: "Engineer working in quant modeling & data risk.",
    years_of_experience: "4",
    tech_stack: ["Python", "SQL", "Jupyter"],
    open_to_roles: ["Quant Engineer", "Data Engineer"],
    availability: "Hybrid",
  },
  {
    skill_tags: ["SaaS Strategy", "Research", "Competitive Analysis"],
    expertise_summary: "Works closely with stakeholders to define strategy.",
    years_of_experience: "2",
    tech_stack: ["Notion", "Mixpanel", "Google Workspace"],
    open_to_roles: ["Associate PM", "Strategy Analyst"],
    availability: "Full-time",
  },
  {
    skill_tags: ["React Native", "Firebase", "Mobile UI"],
    expertise_summary: "Passionate about building modern mobile experiences.",
    years_of_experience: "3",
    tech_stack: ["React Native", "Expo", "Firebase"],
    open_to_roles: ["Mobile Engineer", "Full-Stack Engineer"],
    availability: "Remote",
  },
];

