export const founderStep1Data = [
  {
    full_name: "Arjun Rao",
    profile_photo: "https://randomuser.me/api/portraits/men/10.jpg",
    short_bio: "Entrepreneur passionate about solving real-world inefficiencies with tech.",
    experience_background: "Background in engineering.",
    linkedin_url: "https://linkedin.com/in/arjunrao",
    city: "Bangalore",
    country: "India",
    looking_for: "CTO",
  },
  {
    full_name: "Sofia Martins",
    profile_photo: "https://randomuser.me/api/portraits/women/20.jpg",
    short_bio: "Ex-product manager building user-centric solutions.",
    experience_background: "Background in product and design.",
    linkedin_url: "https://linkedin.com/in/sofiamartins",
    city: "Berlin",
    country: "Germany",
    looking_for: "COO",
  },
  {
    full_name: "Michael Chen",
    profile_photo: "https://randomuser.me/api/portraits/men/21.jpg",
    short_bio: "Technical founder exploring AI solutions.",
    experience_background: "Background in machine learning engineering.",
    linkedin_url: "https://linkedin.com/in/michaelchen",
    city: "San Francisco",
    country: "USA",
    looking_for: "CMO",
  },
  {
    full_name: "Sarah Ibrahim",
    profile_photo: "https://randomuser.me/api/portraits/women/22.jpg",
    short_bio: "Healthcare professional transitioning into digital health entrepreneurship.",
    experience_background: "Background in healthcare and business.",
    linkedin_url: "https://linkedin.com/in/sarahibrahim",
    city: "London",
    country: "UK",
    looking_for: "CTO",
  },
  {
    full_name: "Luis Hernandez",
    profile_photo: "https://randomuser.me/api/portraits/men/23.jpg",
    short_bio: "Passionate about sustainability and climate-focused products.",
    experience_background: "Background in climate research and technology.",
    linkedin_url: "https://linkedin.com/in/luishernandez",
    city: "Barcelona",
    country: "Spain",
    looking_for: "Growth Hacker",
  },

  // --- New 15 handcrafted entries ---

  {
    full_name: "Emily Zhang",
    profile_photo: "https://randomuser.me/api/portraits/women/23.jpg",
    short_bio: "Former Meta engineer building AI-powered collaboration tools.",
    experience_background: "Background in software engineering.",
    linkedin_url: "https://linkedin.com/in/emilyzhang",
    city: "Singapore",
    country: "Singapore",
    looking_for: "Designer",
  },
  {
    full_name: "Jason White",
    profile_photo: "https://randomuser.me/api/portraits/men/30.jpg",
    short_bio: "Startup operator with experience scaling marketplaces from 0 → 1.",
    experience_background: "Background in business and operations.",
    linkedin_url: "https://linkedin.com/in/jasonwhite",
    city: "New York",
    country: "USA",
    looking_for: "CTO",
  },
  {
    full_name: "Aisha Al-Sayed",
    profile_photo: "https://randomuser.me/api/portraits/women/30.jpg",
    short_bio: "Solving problems in logistics and supply chain automation.",
    experience_background: "Background in logistics and lean systems.",
    linkedin_url: "https://linkedin.com/in/aishaalsayed",
    city: "Dubai",
    country: "UAE",
    looking_for: "COO",
  },
  {
    full_name: "Felix Müller",
    profile_photo: "https://randomuser.me/api/portraits/men/31.jpg",
    short_bio: "Exploring automation for industrial and manufacturing sectors.",
    experience_background: "Background in robotics and automation.",
    linkedin_url: "https://linkedin.com/in/felixautomation",
    city: "Munich",
    country: "Germany",
    looking_for: "CTO",
  },
  {
    full_name: "Riya Shah",
    profile_photo: "https://randomuser.me/api/portraits/women/31.jpg",
    short_bio: "Building inclusive tools for financial literacy in emerging markets.",
    experience_background: "Background in finance and fintech product.",
    linkedin_url: "https://linkedin.com/in/riyashah",
    city: "Mumbai",
    country: "India",
    looking_for: "CMO",
  },
  {
    full_name: "Alexander Parker",
    profile_photo: "https://randomuser.me/api/portraits/men/40.jpg",
    short_bio: "Ex-consultant turning gov-tech problems into scalable solutions.",
    experience_background: "Background in government systems and business consulting.",
    linkedin_url: "https://linkedin.com/in/alexparker",
    city: "Toronto",
    country: "Canada",
    looking_for: "COO",
  },
  {
    full_name: "Jade Kim",
    profile_photo: "https://randomuser.me/api/portraits/women/41.jpg",
    short_bio: "Combining psychology & design to build habit-forming products.",
    experience_background: "Background in behavioral science and UX.",
    linkedin_url: "https://linkedin.com/in/jadekim",
    city: "Seoul",
    country: "South Korea",
    looking_for: "Designer",
  },
  {
    full_name: "Mark Evans",
    profile_photo: "https://randomuser.me/api/portraits/men/41.jpg",
    short_bio: "Serial entrepreneur with two exits, now in climate tech.",
    experience_background: "Background in SaaS and product strategy.",
    linkedin_url: "https://linkedin.com/in/markevans",
    city: "Los Angeles",
    country: "USA",
    looking_for: "CMO",
  },
  {
    full_name: "Tara Patel",
    profile_photo: "https://randomuser.me/api/portraits/women/42.jpg",
    short_bio: "Designer founder obsessed with craft + detail.",
    experience_background: "Background in UX and branding.",
    linkedin_url: "https://linkedin.com/in/tarapatel",
    city: "Pune",
    country: "India",
    looking_for: "CTO",
  },
  {
    full_name: "Jean-Luc Moreau",
    profile_photo: "https://randomuser.me/api/portraits/men/43.jpg",
    short_bio: "Building cultural and travel experiences using immersive technology.",
    experience_background: "Background in creative direction.",
    linkedin_url: "https://linkedin.com/in/jeanlucmoreau",
    city: "Paris",
    country: "France",
    looking_for: "CTO",
  },
  {
    full_name: "Helena Silva",
    profile_photo: "https://randomuser.me/api/portraits/women/43.jpg",
    short_bio: "Working to democratize health access with digital care.",
    experience_background: "Background in healthcare and product.",
    linkedin_url: "https://linkedin.com/in/helenasilva",
    city: "Lisbon",
    country: "Portugal",
    looking_for: "COO",
  },
  {
    full_name: "Omar Abdullah",
    profile_photo: "https://randomuser.me/api/portraits/men/44.jpg",
    short_bio: "Building high-impact public education tools.",
    experience_background: "Background in edtech and policy research.",
    linkedin_url: "https://linkedin.com/in/omarabdullah",
    city: "Cairo",
    country: "Egypt",
    looking_for: "CMO",
  },
  {
    full_name: "Chloe Rivera",
    profile_photo: "https://randomuser.me/api/portraits/women/44.jpg",
    short_bio: "Scaling digital operations for fast-moving brands.",
    experience_background: "Background in business operations and growth.",
    linkedin_url: "https://linkedin.com/in/chloerivera",
    city: "Buenos Aires",
    country: "Argentina",
    looking_for: "COO",
  },
];


export const founderStep2Data = [
  {
    startup_name: "Streamline AI",
    one_line_pitch: "Reinventing workflow automation for SMBs.",
    description: "We are building an AI platform that automates internal business processes.",
    industry: "AI Productivity",
    stage: "MVP",
    tech_stack: ["React", "Node.js", "Python", "AWS"],
    website_url: "https://streamline.ai",
    problem_statement: "Solving inefficiency and manual overhead in operations.",
    target_market: "Global",
  },
  {
    startup_name: "MindSync Health",
    one_line_pitch: "AI-powered personalized mental health support.",
    description: "Digitally transforming mental wellness through guided therapy and NLP.",
    industry: "HealthTech",
    stage: "Idea",
    tech_stack: ["Python", "TensorFlow", "Flutter"],
    website_url: "https://mindsync.health",
    problem_statement: "Lack of accessible mental health guidance at scale.",
    target_market: "India",
  },
  {
    startup_name: "Logiflow",
    one_line_pitch: "Real-time AI optimization for warehouse operations.",
    description: "We help logistics companies reduce delays using predictive decision models.",
    industry: "Mobility",
    stage: "Seed",
    tech_stack: ["AWS", "Node.js", "Go", "PostgreSQL"],
    website_url: "https://logiflow.com",
    problem_statement: "Slow dispatch operations increase delivery cost and delays.",
    target_market: "USA & Europe",
  },
  {
    startup_name: "EduLeap",
    one_line_pitch: "Empowering learning with adaptive assessments.",
    description: "Collaborative learning ecosystem for students and educators.",
    industry: "EdTech",
    stage: "Growth",
    tech_stack: ["React", "Firebase", "Python"],
    website_url: "https://eduleap.school",
    problem_statement: "Static learning does not account for student speed or difficulty.",
    target_market: "Global",
  },
  {
    startup_name: "CarbonSense",
    one_line_pitch: "Smart sustainability tracking for organizations.",
    description: "Automating sustainability compliance and real-time emission tracking.",
    industry: "ClimateTech",
    stage: "MVP",
    tech_stack: ["Next.js", "AWS", "Python"],
    website_url: "https://carbonsense.io",
    problem_statement: "Businesses lack simple carbon reporting tools.",
    target_market: "EU",
  },

  // --- Remaining handcrafted 15 startups ---

  {
    startup_name: "FlowOS",
    one_line_pitch: "Supercharging remote teams with context-aware tooling.",
    description: "We build AI-powered communication intelligence for distributed teams.",
    industry: "Collaboration Software",
    stage: "Seed",
    tech_stack: ["React", "Supabase", "OpenAI API", "Python"],
    website_url: "https://flowos.co",
    problem_statement: "Remote teams lose context and alignment across tools.",
    target_market: "Global",
  },
  {
    startup_name: "EduChain",
    one_line_pitch: "Blockchain-verified academic credentials.",
    description: "Decentralized system for verifying identity and certificates.",
    industry: "Blockchain",
    stage: "Idea",
    tech_stack: ["Solidity", "Next.js", "Polygon"],
    website_url: "https://educhain.org",
    problem_statement: "Fraudulent certificates and lack of trusted verification.",
    target_market: "Asia & Europe",
  },
  {
    startup_name: "RetailPulse",
    one_line_pitch: "Predictive analytics for fast retail decisions.",
    description: "Smart platform analyzing customer habit trends using AI.",
    industry: "RetailTech",
    stage: "Series A",
    tech_stack: ["Python", "Snowflake", "Next.js"],
    website_url: "https://retailpulse.ai",
    problem_statement: "Retailers lack real-time actionable insights.",
    target_market: "North America",
  },
  {
    startup_name: "FinBridge",
    one_line_pitch: "Bringing accessible wealth tools to developing markets.",
    description: "Mobile platform with robo-advisory and micro-investments.",
    industry: "FinTech",
    stage: "MVP",
    tech_stack: ["React Native", "AWS", "FastAPI"],
    website_url: "https://finbridge.app",
    problem_statement: "Savings & investments remain inaccessible in emerging economies.",
    target_market: "India & Africa",
  },
  {
    startup_name: "XR StoryLab",
    one_line_pitch: "Immersive storytelling using AR/VR experiences.",
    description: "A creator platform enabling spatial augmented reality publishing.",
    industry: "MediaTech",
    stage: "Idea",
    tech_stack: ["Unity", "Three.js", "Firebase"],
    website_url: "https://xrstorylab.io",
    problem_statement: "Creators lack tools to build high-quality immersive content.",
    target_market: "Global",
  },
  {
    startup_name: "ClimaLabs",
    one_line_pitch: "AI-based monitoring for environmental compliance.",
    description: "Tracking infrastructure to help governments monitor environmental rules.",
    industry: "GovTech",
    stage: "Seed",
    tech_stack: ["Python", "GIS", "Node.js"],
    website_url: "https://climalabs.ai",
    problem_statement: "Manual environmental audits are slow and inaccurate.",
    target_market: "Middle East & Asia",
  },
  {
    startup_name: "CraftOS",
    one_line_pitch: "Human-centered e-commerce tools for handmade businesses.",
    description: "Helping small creators manage storefronts with automation.",
    industry: "E-Commerce",
    stage: "Growth",
    tech_stack: ["Shopify API", "Next.js", "PostgreSQL"],
    website_url: "https://craftos.store",
    problem_statement: "Independent craftsmen lack scalable digital tools.",
    target_market: "India, US, UK",
  },
  {
    startup_name: "MobiFleet",
    one_line_pitch: "Smart fleet routing and cost optimization.",
    description: "AI-powered live route and maintenance prediction.",
    industry: "Mobility",
    stage: "Seed",
    tech_stack: ["Go", "AWS IoT", "React"],
    website_url: "https://mobifleet.ai",
    problem_statement: "Fleet operations are costly and inefficient.",
    target_market: "Logistics Companies",
  },
  {
    startup_name: "NeuronPay",
    one_line_pitch: "AI-powered anti-fraud for transactions.",
    description: "Fraud detection using real-time behavior modeling.",
    industry: "FinTech",
    stage: "Series A",
    tech_stack: ["Python", "Kafka", "PostgreSQL"],
    website_url: "https://neuronpay.com",
    problem_statement: "Banks struggle with transaction fraud at scale.",
    target_market: "Global",
  },
  {
    startup_name: "EcoNest",
    one_line_pitch: "Sustainable housing marketplace.",
    description: "Connecting eco-friendly builders, architects, and homeowners.",
    industry: "ClimateTech",
    stage: "Idea",
    tech_stack: ["Next.js", "Firebase", "Stripe API"],
    website_url: "https://econest.org",
    problem_statement: "Homeowners lack access to verified sustainable solutions.",
    target_market: "EU & US",
  },
  {
    startup_name: "WellSphere",
    one_line_pitch: "Community-powered wellness ecosystem.",
    description: "Combining AI health monitoring with community support.",
    industry: "HealthTech",
    stage: "Seed",
    tech_stack: ["Python", "React Native", "AWS"],
    website_url: "https://wellsphere.app",
    problem_statement: "Preventive health insights are fragmented and inaccessible.",
    target_market: "Asia & US",
  },
];
